In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from pathlib import Path
import platform
import h5py
import beautifuljason as bjason
import json

import numpy as np
import pandas as pd

In [3]:
fn_assigned = Path("alpha_ionone_assigned_by_jason.jjh5")
fn_unassigned = Path("alpha_ionone_unassigned.jjh5")

fn_simpleNMR_json = Path("alpha_ionone_unassigned_assignments_from_simplemnova.json")

In [4]:
fn_simpleNMR_json.exists(), fn_simpleNMR_json.name

(False, 'alpha_ionone_unassigned_assignments_from_simplemnova.json')

In [112]:
with open(fn_simpleNMR_json, 'r') as f:
    json_data = json.load(f)

In [113]:
json_data.keys()

dict_keys(['nodes_orig', 'nodes_now', 'links', 'smilesString', 'molfile', 'dataFrom', 'oldjsondata', 'molgraph', 'shortest_paths', 'svg', 'catoms', 'catoms_orig', 'best_results', 'workingDirectory', 'workingFilename', 'title'])

In [114]:
json_data['nodes_now'][1]

{'atomNumber': 2,
 'id': 1,
 'iupacLabel': '',
 'jCouplingClass': '',
 'jCouplingVals': '',
 'numProtons': 1,
 'ppm': 148.92451256333828,
 'ppm_calculated': 148.25,
 'sym_atomNumber': '',
 'sym_atom_idx': '',
 'symbol': 'C',
 'visible': True,
 'x': 0.5,
 'y': 0.630666069386199,
 'H1_ppm': [6.592629998578599]}

In [115]:
nodes_now_df = (
    pd.DataFrame.from_dict(nodes_now, orient="index")
    .sort_index()
    .reset_index(drop=True)
)

nodes_now_df

,atomNumber,id,iupacLabel,jCouplingClass,jCouplingVals,numProtons,ppm,ppm_calculated,sym_atomNumber,sym_atom_idx,symbol,visible,x,y,H1_ppm
0,1,0,,,,0,198.310812,197.199997,,,C,True,0.797152,0.630666,NaN
1,2,1,,,,1,148.924513,148.250000,,,C,True,0.500000,0.630666,[6.592629998578599]
2,3,2,,,,1,132.271062,132.449997,,,C,True,0.648582,0.487700,[6.028248356321251]
3,4,3,,,,0,131.840154,132.050003,,,C,True,0.351430,0.201768,NaN
4,5,4,,,,1,122.594516,122.550003,,,C,True,0.202848,0.058802,[5.477035761473378]
5,6,5,,,,1,54.248267,54.250000,,,C,True,0.351430,0.487700,[2.2606984117425166]
6,7,6,,,,0,32.457957,32.400002,,,C,True,0.202848,0.630666,NaN
7,8,7,,,,2,31.172063,29.900002,,,C,True,0.054266,0.487700,"[1.4387920085966683, 1.207638662513644]"
8,9,8,,,,3,27.739804,27.361111,9,10,C,True,0.313126,0.849709,[0.8303538907459487]
9,10,9,,,,3,26.881624,27.100000,,,C,True,0.945734,0.487700,[2.230905472435987]
10,11,10,,,,3,26.746096,27.361111,11,8,C,True,0.092581,0.849709,[0.9074050061069573]
11,12,11,,,,2,22.961698,23.044445,,,C,True,0.054266,0.201768,[2.0267750995283533]
12,13,12,,,,3,22.711646,22.862501,,,C,True,0.500000,0.058802,[1.5450694090946102]

In [116]:
nodes_now_df.dtypes

atomNumber          int64
id                  int64
iupacLabel         object
jCouplingClass     object
jCouplingVals      object
numProtons          int64
ppm               float64
ppm_calculated    float64
sym_atomNumber     object
sym_atom_idx       object
symbol             object
visible              bool
x                 float64
y                 float64
H1_ppm             object
dtype: object

### Convert the nans in the H1_ppm column to empty lists

In [117]:
nodes_now_df["H1_ppm"] = nodes_now_df["H1_ppm"].apply(
    lambda x: [] if x is None or (isinstance(x, float) and pd.isna(x)) else x
)

nodes_now_df["H1_ppm"].head()

0                     []
1    [6.592629998578599]
2    [6.028248356321251]
3                     []
4    [5.477035761473378]
Name: H1_ppm, dtype: object

### For CH<sub>2</sub> protons make sure the number of ppm values in the H1_ppm list is 2

In [118]:
for i, row in nodes_now_df.iterrows():
    if row["numProtons"] == 2 and len(row["H1_ppm"]) == 1:
        nodes_now_df.at[i, "H1_ppm"] = row["H1_ppm"] * 2

nodes_now_df["H1_ppm"]

0                                           []
1                          [6.592629998578599]
2                          [6.028248356321251]
3                                           []
4                          [5.477035761473378]
5                         [2.2606984117425166]
6                                           []
7      [1.4387920085966683, 1.207638662513644]
8                         [0.8303538907459487]
9                          [2.230905472435987]
10                        [0.9074050061069573]
11    [2.0267750995283533, 2.0267750995283533]
12                        [1.5450694090946102]
Name: H1_ppm, dtype: object

In [119]:
pd.__version__

'2.2.3'

### Add a column for the JEOL calculated protons called H1_ppm_calc

In [120]:
nodes_now_df['H1_ppm_calc'] = nodes_now_df.apply(lambda _: [], axis=1)
nodes_now_df

,atomNumber,id,iupacLabel,jCouplingClass,jCouplingVals,numProtons,ppm,ppm_calculated,sym_atomNumber,sym_atom_idx,symbol,visible,x,y,H1_ppm,H1_ppm_calc
0,1,0,,,,0,198.310812,197.199997,,,C,True,0.797152,0.630666,[],[]
1,2,1,,,,1,148.924513,148.250000,,,C,True,0.500000,0.630666,[6.592629998578599],[]
2,3,2,,,,1,132.271062,132.449997,,,C,True,0.648582,0.487700,[6.028248356321251],[]
3,4,3,,,,0,131.840154,132.050003,,,C,True,0.351430,0.201768,[],[]
4,5,4,,,,1,122.594516,122.550003,,,C,True,0.202848,0.058802,[5.477035761473378],[]
5,6,5,,,,1,54.248267,54.250000,,,C,True,0.351430,0.487700,[2.2606984117425166],[]
6,7,6,,,,0,32.457957,32.400002,,,C,True,0.202848,0.630666,[],[]
7,8,7,,,,2,31.172063,29.900002,,,C,True,0.054266,0.487700,"[1.4387920085966683, 1.207638662513644]",[]
8,9,8,,,,3,27.739804,27.361111,9,10,C,True,0.313126,0.849709,[0.8303538907459487],[]
9,10,9,,,,3,26.881624,27.100000,,,C,True,0.945734,0.487700,[2.230905472435987],[]
10,11,10,,,,3,26.746096,27.361111,11,8,C,True,0.092581,0.849709,[0.9074050061069573],[]
11,12,11,,,,2,22.961698,23.044445,,,C,True,0.054266,0.201768,"[2.0267750995283533, 2.0267750995283533]",[]
12,13,12,,,,3,22.711646,22.862501,,,C,True,0.500000,0.058802,[1.5450694090946102],[]

In [121]:
print(nodes_now_df['H1_ppm_calc'].dtype)
print(nodes_now_df.at[row_label, 'H1_ppm_calc'])
print(type(nodes_now_df.at[row_label, 'H1_ppm_calc']))

object
[]
<class 'list'>

In [ ]:
with bjason.Document(fn_unassigned, mode="r+") as doc:

    c13_spec, h1_spec = find_molecule_spectra(doc)
    for shift in h1_spec.shifts:
        h1_calc_shift_value, _ = shift.get_value_error_pair(
                bjason.Molecule.CalcMethod.Best,
        )
        print(f"h1_calc_shift_value: {h1_calc_shift_value}, shift.nums: {shift.nums[0]}")
        id = shift.nums[0] if len(shift.nums) > 0 else None
        print(f"id: {id}, type(id): {type(id)}")
        if id is not None:
            # append to the list in the 'H1_ppm_calc' column for the row with the matching 'id'
            matching_idx = nodes_now_df.index[nodes_now_df['id'] == id]
            if len(matching_idx) > 0:
                row_label = matching_idx[0]
                nodes_now_df.at[row_label, 'H1_ppm_calc'].append(h1_calc_shift_value)
nodes_now_df[['id', 'numProtons', 'H1_ppm', 'H1_ppm_calc']]

h1_calc_shift_value: 0.8600000143051147, shift.nums: 8
id: 8, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 2.259999990463257, shift.nums: 9
id: 9, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 0.8600000143051147, shift.nums: 10
id: 10, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 1.5800000429153442, shift.nums: 12
id: 12, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 6.5302734375, shift.nums: 1
id: 1, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 6.090000152587891, shift.nums: 2
id: 2, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 5.460000038146973, shift.nums: 4
id: 4, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 2.48876953125, shift.nums: 5
id: 5, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 1.2568359375, shift.nums: 7
id: 7, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 1.5322265625, shift.nums: 7
id: 7, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 2.04931640625, shift.nums: 11
id: 11, type(id): <class 'numpy.uint32'>
h1_calc_shift_value: 2.04931640625, shift.nums: 11
id: 11, type(id): <class 'numpy.uint32'>

    id                                    H1_ppm             H1_ppm_calc
0    0                                        []                      []
1    1                       [6.592629998578599]             [6.5302734]
2    2                       [6.028248356321251]                  [6.09]
3    3                                        []                      []
4    4                       [5.477035761473378]                  [5.46]
5    5                      [2.2606984117425166]             [2.4887695]
6    6                                        []                      []
7    7   [1.4387920085966683, 1.207638662513644]  [1.2568359, 1.5322266]
8    8                      [0.8303538907459487]                  [0.86]
9    9                       [2.230905472435987]                  [2.26]
10  10                      [0.9074050061069573]                  [0.86]
11  11  [2.0267750995283533, 2.0267750995283533]  [2.0493164, 2.0493164]
12  12                      [1.5450694090946102]                  [1.58]

In [123]:
nodes_now_df[['id', 'numProtons', 'H1_ppm', 'H1_ppm_calc']]

,id,numProtons,H1_ppm,H1_ppm_calc
0,0,0,[],[]
1,1,1,[6.592629998578599],[6.5302734]
2,2,1,[6.028248356321251],[6.09]
3,3,0,[],[]
4,4,1,[5.477035761473378],[5.46]
5,5,1,[2.2606984117425166],[2.4887695]
6,6,0,[],[]
7,7,2,"[1.4387920085966683, 1.207638662513644]","[1.2568359, 1.5322266]"
8,8,3,[0.8303538907459487],[0.86]
9,9,3,[2.230905472435987],[2.26]
10,10,3,[0.9074050061069573],[0.86]
11,11,2,"[2.0267750995283533, 2.0267750995283533]","[2.0493164, 2.0493164]"
12,12,3,[1.5450694090946102],[1.58]

In [8]:
nodes_now = {}
for node in json_data['nodes_now']:
    id = int(node['id'])
    nodes_now[id] = node

In [9]:
nodes_now.keys()

dict_keys([0, 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
for node_id, node in nodes_now.items():
    print(f"{node_id:2}: {node['ppm']:7.2f}")

 0:  198.31
 1:  148.92
10:   26.75
11:   22.96
12:   22.71
 2:  132.27
 3:  131.84
 4:  122.59
 5:   54.25
 6:   32.46
 7:   31.17
 8:   27.74
 9:   26.88

In [54]:
def find_molecule_spectra( doc):
    # return carbon mol spec and proton mol spec as a tuple
    mol = doc.mol_data[0]
    c13_spec = None
    h1_spec = None
    for spec in mol.spectra:
        if spec.nucleus == bjason.Molecule.Atom.NuclType.C13:
            c13_spec = spec
        elif spec.nucleus == bjason.Molecule.Atom.NuclType.H1:
            h1_spec = spec
    return c13_spec, h1_spec

In [55]:
with bjason.Document(fn_unassigned, mode="r+") as doc:
    mol = doc.mol_data[0]
    print(type(mol))
    print(type(mol.spectra))
    for spec in mol.spectra:
        print(type(spec), spec.nucleus, bjason.Molecule.Atom.NuclType.C13, bjason.Molecule.Atom.NuclType.H1)

<class 'beautifuljason.data.Molecule'>
<class 'beautifuljason.data.Molecule.Spectrum.List'>
<class 'beautifuljason.data.Molecule.Spectrum'> 10 10 1
<class 'beautifuljason.data.Molecule.Spectrum'> 1 10 1

In [82]:
with bjason.Document(fn_unassigned, mode="r+") as doc:

    c13_spec, h1_spec = find_molecule_spectra(doc)
    print(f"c13_spec.shifts: {len(c13_spec.shifts)}, h1_spec.shifts: {len(h1_spec.shifts)}")
    for shift in h1_spec.shifts:
        print(f"h1 shift.nums: {shift.nums}")

    for shift in c13_spec.shifts:
        print(f"c13 shift.nums: {shift.nums}")
    print(h1_spec.shifts[0].nums)

c13_spec.shifts: 13, h1_spec.shifts: 12
h1 shift.nums: [8]
h1 shift.nums: [9]
h1 shift.nums: [10]
h1 shift.nums: [12]
h1 shift.nums: [1]
h1 shift.nums: [2]
h1 shift.nums: [4]
h1 shift.nums: [5]
h1 shift.nums: [7]
h1 shift.nums: [7]
h1 shift.nums: [11]
h1 shift.nums: [11]
c13 shift.nums: [0]
c13 shift.nums: [1]
c13 shift.nums: [2]
c13 shift.nums: [3]
c13 shift.nums: [4]
c13 shift.nums: [5]
c13 shift.nums: [6]
c13 shift.nums: [7]
c13 shift.nums: [8]
c13 shift.nums: [9]
c13 shift.nums: [10]
c13 shift.nums: [11]
c13 shift.nums: [12]
[8]

In [79]:
h1_spec.shifts[0]

IndexError: List index out of range

In [72]:
for shift in h1_spec.shifts:
    print(f"shift.nums: {shift.nums}, shift.ppm: {shift.ppm}, shift.intensity: {shift.intensity}")

In [ ]:
# create a pandas data frame to hold the data coming from the simplenmr json file

In [63]:
# add column titles
print(f"{'ID':3} {'#H':5} {'C13 Calc':7} {'C13 Exp':7} {'H1 Exp':10}")
print("-" * 30)
with bjason.Document(fn_unassigned, mode="r+") as doc:

    c13_spec, h1_spec = find_molecule_spectra(doc)

    for c13_shift, h1_shift in zip(c13_spec.shifts, h1_spec.shifts):
        c13_calc_shift_value, _ = c13_shift.get_value_error_pair(
                bjason.Molecule.CalcMethod.Best,
        )
        h1_calc_shift_value, _ = h1_shift.get_value_error_pair(
                bjason.Molecule.CalcMethod.Best,
        )
        atom_id = c13_shift.nums[0]
        numProtons = int(nodes_now[atom_id].get('numProtons', 0))
        H1_ppms = nodes_now[atom_id].get('H1_ppm', [])
        # convert list into a string, filtering out None values
        if numProtons == 2 and len(H1_ppms) == 1:
            H1_ppms = [H1_ppms[0], H1_ppms[0]]
        h1_ppm_str = ",".join(f"{h1_ppm:5.2f}" for h1_ppm in H1_ppms if h1_ppm is not None)
        print(f"{c13_shift.nums[0]:2}: {numProtons:2} {calc_shift_value:10.2f} {nodes_now[atom_id]['ppm']:8.2f} {h1_ppm_str}")

ID  #H    C13 Calc C13 Exp H1 Exp
------------------------------
 0:  0      23.04   198.31
 1:  1      23.04   148.92  6.59
 2:  1      23.04   132.27  6.03
 3:  0      23.04   131.84
 4:  1      23.04   122.59  5.48
 5:  1      23.04    54.25  2.26
 6:  0      23.04    32.46
 7:  2      23.04    31.17  1.44, 1.21
 8:  3      23.04    27.74  0.83
 9:  3      23.04    26.88  2.23
10:  3      23.04    26.75  0.91
11:  2      23.04    22.96  2.03, 2.03

In [17]:
dir(shift)

['List',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_attr',
 'acount',
 'error_spheres',
 'get_value_error_pair',
 'h5_group',
 'ignored_auto',
 'ignored_user',
 'is_exchangeable',
 'mark',
 'nh',
 'nums',
 'set_value_error_pair',
 'value',
 'value_error',
 'value_method',
 'value_spheres']

In [24]:
with bjason.Document(fn_unassigned, mode="r+") as doc:
    mol = doc.mol_data[0]
    spec = mol.spectra[0]

    for shift in spec.shifts:

        print(shift.nums)
        shift.set_value_error_pair(
            bjason.Molecule.CalcMethod.Experimental,
            nodes_now[shift.nums[0]]['ppm'],
        )

[0]
[1]
[2]
[3]
[4]
[5]
[6]
[7]
[8]
[9]
[10]
[11]
[12]

In [43]:
fn_assigned.exists(), fn_unassigned.exists()

(True, True)

In [47]:
with bjason.Document(fn_assigned, mode="r") as doc:
    print(type(doc.mol_data), "\n", dir(doc.mol_data))

<class 'beautifuljason.data.Molecule.List'>
 ['Iterator', '__bool__', '__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__firstlineno__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__setattr__', '__sizeof__', '__static_attributes__', '__str__', '__subclasshook__', '__weakref__', '_attr', '_len', 'append', 'h5_group', 'list_group_name', 'value_class']

In [ ]:

with bjason.Document(fn_unassigned, mode="r") as doc:
    print(f"number of molecules: {len(doc.mol_data)}")


    mol = doc.mol_data[0]
    print(f"number of spectra: {len(mol.spectra)}")
    # spec = mol.spectra[0]

    for ispec, spec in enumerate(mol.spectra):
        # print out the nuclues type of the spectra
        if spec.nucleus == bjason.Molecule.Atom.NuclType.H1:
            print(f"spectra {ispec} nucleus: H1")
        elif spec.nucleus == bjason.Molecule.Atom.NuclType.C13:
            print(f"spectra {ispec} nucleus: C13")
        else:
            continue

        for shift in spec.shifts:
            calc_shift_value, _ = shift.get_value_error_pair(
                bjason.Molecule.CalcMethod.Experimental, 
            )
            for num in shift.nums:
                element = "H" if spec.nucleus == bjason.Molecule.Atom.NuclType.H1 else "C"
                aid = element + str(num) + (f"({shift.mark})" if shift.mark else "")
                print(aid, calc_shift_value)

number of molecules: 1
number of spectra: 2
spectra 0 nucleus: C13
C0 197.2
C1 148.25
C2 132.45
C3 132.05
C4 122.55
C5 54.25
C6 32.4
C7 29.900002
C8 27.36111
C9 27.1
C10 27.36111
C11 23.044445
C12 22.862501
spectra 1 nucleus: H1
H8 0.86
H9 2.26
H10 0.86
H12 1.58
H1 6.5302734
H2 6.09
H4 5.46
H5 2.4887695
H7(dn) 1.2568359
H7(up) 1.5322266
H11(dn) 2.0493164
H11(up) 2.0493164

In [ ]:

with bjason.Document(fn_assigned, mode="r") as doc:
    mol = doc.mol_data[0]
    spec = mol.spectra[0]

    for shift in spec.shifts:
        value, _ = shift.get_value_error_pair(
            bjason.Molecule.CalcMethod., 
        )
        if value is not None:
            print(list(shift.nums), shift.nh, shift.mark, value, shift.value)

[np.uint32(0)] 0 None 197.2 [198.3108  198.01193 197.7539  197.2     197.2    ]
[np.uint32(1)] 1 None 148.25 [148.92451 147.93091 147.94922 148.25    148.25   ]
[np.uint32(2)] 1 None 132.45 [132.27106 133.10081 132.44629 132.45    132.45   ]
[np.uint32(3)] 0 None 132.05 [131.84015 132.65195 131.22559 132.05    132.05   ]
[np.uint32(4)] 1 None 122.55 [122.59451  122.61086  122.680664 122.55     122.55    ]
[np.uint32(5)] 1 None 54.25 [54.24827  56.50496  53.527832 54.25     54.25    ]
[np.uint32(6)] 0 None 32.4 [32.45796  34.327927 32.53174  32.4      32.4     ]
[np.uint32(7)] 2 None 29.900002 [31.172062 34.607113 30.151367 29.900002 29.900002]
[np.uint32(8)] 3 None 27.36111 [27.739805 26.21915  27.023315 27.36111  27.36111 ]
[np.uint32(9)] 3 None 27.1 [26.881624 27.89914  27.175903 27.1      27.1     ]
[np.uint32(10)] 3 None 27.36111 [26.746096 26.21915  27.023315 27.36111  27.36111 ]
[np.uint32(11)] 2 None 23.044445 [22.961699 22.827124 22.964478 23.044445 23.044445]
[np.uint32(12)] 3 None 22.862501 [22.711645 22.699148 22.827148 22.862501 22.862501]

In [15]:
dir(shift)

['List',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_attr',
 'acount',
 'error_spheres',
 'get_value_error_pair',
 'h5_group',
 'ignored_auto',
 'ignored_user',
 'is_exchangeable',
 'mark',
 'nh',
 'nums',
 'set_value_error_pair',
 'value',
 'value_error',
 'value_method',
 'value_spheres']

In [13]:
type(bjason.Molecule.CalcMethod.Experimental), dir(bjason.Molecule.CalcMethod.Experimental)

(<enum 'CalcMethod'>,
 ['Best',
  'Experimental',
  'Increment',
  'NeuralNetwork',
  'SphericCodes',
  'Undefined',
  '__abs__',
  '__add__',
  '__and__',
  '__bool__',
  '__ceil__',
  '__class__',
  '__copy__',
  '__deepcopy__',
  '__delattr__',
  '__dict__',
  '__dir__',
  '__divmod__',
  '__doc__',
  '__eq__',
  '__float__',
  '__floor__',
  '__floordiv__',
  '__format__',
  '__ge__',
  '__getattribute__',
  '__getnewargs__',
  '__getstate__',
  '__gt__',
  '__hash__',
  '__index__',
  '__init__',
  '__init_subclass__',
  '__int__',
  '__invert__',
  '__le__',
  '__lshift__',
  '__lt__',
  '__mod__',
  '__module__',
  '__mul__',
  '__ne__',
  '__neg__',
  '__new__',
  '__objclass__',
  '__or__',
  '__pos__',
  '__pow__',
  '__radd__',
  '__rand__',
  '__rdivmod__',
  '__reduce__',
  '__reduce_ex__',
  '__repr__',
  '__rfloordiv__',
  '__rlshift__',
  '__rmod__',
  '__rmul__',
  '__ror__',
  '__round__',
  '__rpow__',
  '__rrshift__',
  '__rshift__',
  '__rsub__',
  '__rtruediv__',
  '__rxor__',
  '__setattr__',
  '__signature__',
  '__sizeof__',
  '__str__',
  '__sub__',
  '__subclasshook__',
  '__truediv__',
  '__trunc__',
  '__weakref__',
  '__xor__',
  '_generate_next_value_',
  '_member_map_',
  '_member_names_',
  '_member_type_',
  '_missing_',
  '_name_',
  '_new_member_',
  '_sort_order_',
  '_unhashable_values_',
  '_use_args_',
  '_value2member_map_',
  '_value_',
  '_value_repr_',
  'as_integer_ratio',
  'bit_count',
  'bit_length',
  'conjugate',
  'denominator',
  'from_bytes',
  'imag',
  'is_integer',
  'name',
  'numerator',
  'real',
  'to_bytes',
  'value'])

In [15]:
dir(doc)

['__class__',
 '__del__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_create_item_elem',
 'all_logfile_paths',
 'close',
 'copy',
 'create_chart_item',
 'create_document_id',
 'create_image_data',
 'create_image_item',
 'create_mscentroid_table',
 'create_mspeaks_table',
 'create_nmrassignments_table',
 'create_nmrdosy_table',
 'create_nmrmultiplet_report',
 'create_nmrmultiplets_table',
 'create_nmrparams_table',
 'create_nmrpeaks_table',
 'create_params_table',
 'create_text_item',
 'custom_data',
 'document_id',
 'file_name',
 'h5_file',
 'image_data',
 'is_temporary',
 'items',
 'items_by_type',
 'load',
 'logfile_path',
 'mol_data',
 'mol_items',
 'ms_data',
 'ms_items',
 'nmr_data',
 'nmr_items',
 'page_margin',
 'remove',
 'text_data']

In [7]:
with bjason.Document(fn_unassigned, "r") as doc:
    mol = doc.mol_data[0]
    spec = mol.spectra[0]

    for shift in spec.shifts:
        value, _ = shift.get_value_error_pair(
            bjason.Molecule.CalcMethod.Experimental
        )
        if value is not None:
            print(list(shift.nums), shift.mark, value)

In [9]:
with bjason.Document(fn_unassigned, "r") as doc:
    mol = doc.mol_data[0]
    spec = mol.spectra[0]

    print(dir(spec))

IndexError: List index out of range